spec_version: 2

release:
  # 发布版本号
  version: 1.0.0
  title: "这是一个测试"
  comment: "这是一个测试"

apigateway:
  description: "这是一个测试"
  description_en: "This is a test"
  is_public: false
  maintainers:
    - "admin"

stages:
  - name: "prod"
    description: "这是一个测试"
    description_en: "This is a test"
    proxy_http:
      timeout: 60
      upstreams:
        loadbalance: "roundrobin"
        hosts:
          - host: "https://httpbin.org"
            weight: 100
    # 环境插件配置
    # plugin_configs:
    #     - type: bk-rate-limit
    #       yaml: |-
    #         rates:
    #           __default:
    #           - period: 1
    #             tokens: 100
    #     - type: bk-header-rewrite
    #       yaml: |-
    #         set:
    #           - key: test
    #             value: '2'
    #         remove: []
    #     - type: bk-cors
    #       yaml: |-
    #         allow_origins: '*'
    #         allow_methods: '*'
    #         allow_headers: '*'
    #         expose_headers: '*'
    #         max_age: 86400
    #         allow_credential: false



# 资源文档
# 资源文档的目录格式样例如下，en 为英文文档，zh 为中文文档：
# ./
# - en
#   - anything.md
# - zh
#   - anything.md
resource_docs:
  basedir: "/data/apidocs/"

# 主动授权，网关主动给应用，添加访问网关所有资源的权限
grant_permissions:
  - bk_app_code: "{{ settings.BK_APP_CODE }}"
    grant_dimension: "gateway"
