name: bkapi-client-core

on:
  push:
    branches:
      - master
    paths:
      - "sdks/bkapi-client-core/**"
  pull_request:
    branches:
      - "master"
    paths:
      - "sdks/bkapi-client-core/**"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7", "3.7"]
        os: [ubuntu-18.04, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'sdks/bkapi-client-core/requirements_tox.txt'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install 'tox==3.23.0' 'tox-gh-actions==2.12.0'

    - name: Test with tox
      run: tox
      working-directory: sdks/bkapi-client-core
